@startuml original structure

interface TableMetaInfo {

}

interface TransformationResult {
    String databasePath;
    TableMetaInfo tableMetaInfo;
}

class DashboardDataSource {
    -String id;
    -String dataSourcePath;
    -String type;
    -String databasePath;
    -Strind dataSourceName;
    -TableMetaInfo tableMetaInfo;
}

TableMetaInfo ..> TransformationResult
TableMetaInfo ..> DashboardDataSource

class TransformationConfig<C extends DashboardDataSource> {
    -C dataSouce;

    +Observable<TransformationResult> finalResult()
}
TransformationResult ..> TransformationConfig

interface TransformationDashboard {
    -String selectedDataSourceId;
    -TransformationConfig[] configs;
}

TransformationConfig ..> TransformationDashboard
class AppStore {
    -DashboardDataSource[] dataSources;
    -TransformationDashboard transformationDashboard;

    +Observable<TransformationConfig> selectedTransformationConfig()
    +void updateDataSourceResult(DashboardDataSource dataSource, Observable<TransformationResult> result)
}

TransformationDashboard ..> AppStore
DashboardDataSource ..> AppStore
@enduml