@startuml convert-transformation-to-job
skinparam DefaultTextAlignment center

title Convert Transformation Groups to Jobs
(*) --> [Transformation Groups]"Initialize Job queue"
--> [For each Transformation Group]"Initialize local deps"

if "Has dependency" then
    --> [true] "push -1 to deps\npush (-1 - size(group)) to deps "
    --> "Handle dependency group"
    --r-> [push to job queue]"Initialize local deps"
else
    --> [false] "push the first transformation to job queue with deps"
    --> "push other transformations to job queue with [-1]"
    --> [Finish](*)
endif
@enduml