@startuml data-source-transformation

left to right direction

interface Transformation {
    result: TransformationResult
}

interface TransformationGroup {
    transformation: Transformation[]
    dependencies?: TransformationGroup
}

interface TableMetaInfo {

}

interface TransformationResultData {
    databasePath: string
    tableMetaInfo: TableMetaInfo
    query?: string
}

interface TransformationResult {
    status: 'READY' | 'ERROR' | 'Loading'
    data?: TransformationResultData
    error?: string
}

TableMetaInfo ..> TransformationResultData
TransformationResultData ..> TransformationResult
TransformationResult ..r-> Transformation

class TransformationCreate {
    type: 'Create'
    fileType: 'CSV' | 'D4C'
    filePath: string
}

class TransformationAddRows {
    type: 'ADD_ROWS'
    matchColumns: [string, string][]
}

class TransformationAddColumns {
    type: 'ADD_COLUMNS'
    matchColumns: [string, string][]
    joinMode: 'inner' | 'full' | 'left' | 'right'
}

class TransformationAddCalculatedColumn {
    type: 'ADD_CALCULATED_COLUMN'
    expression: string
    columnName: string
}

class TransformationFilter {
    type: 'Filter'
}

class TransformationSample {
    type: 'Sample'
}

class TransformationInterpolation {
    type: 'Interpolation'
}

interface DataSource {
    id: string
    name: string
    transformations: TransformationGroup[]
}
TransformationCreate -d-> Transformation
TransformationAddRows -d-> Transformation
TransformationAddColumns -d-> Transformation
TransformationAddCalculatedColumn -u-> Transformation
TransformationFilter -l-> Transformation
TransformationSample -l-> Transformation
TransformationInterpolation -u-> Transformation

Transformation ..> TransformationGroup
TransformationGroup ..> TransformationGroup
TransformationGroup ..> DataSource
@enduml