@startuml data-sourc-job
left to right direction

interface DataSourceAddCalculatedColumnOperation {

}
 interface DataSourceAddFilterOperation {

 }

class AddCalculatedColumnJob {
    type: 'ADD_CALCULATED_COLUMN_JOB'
    job: DataSourceAddCalculatedColumnOperation
}

class AddFilterJob {
    type: 'ADD_FILTER_JOB'
    job: DataSourceAddFilterOperation
}

interface DataSourceCreateTransfomration {

}

interface DataSourceAddRowsTransformation {

}

interface DataSourceAddColumnsTransformation {

}

class CreateTransformationJob {
    type: 'CREATE_JOB'
    job: Omit<DataSourceCreateTransfomration, 'operations' | 'dependency'>
}

class AddRowsTransformationJob {
    type: 'ADD_ROWS_JOB'
    job: Omit<DataSourceAddRowsTransformation, 'operations' | 'dependency'>
    sourceDependency: number
}

class AddColumnsTransformationJob {
    type: 'ADD_COLUMNS_JOB'
    job: Omit<DataSourceAddColumnsTransformation, 'operations' | 'dependency'>
    sourceDependency: number
}

DataSourceAddColumnsTransformation ..> AddColumnsTransformationJob
DataSourceAddRowsTransformation ..> AddRowsTransformationJob
DataSourceCreateTransfomration ..> CreateTransformationJob
DataSourceAddFilterOperation ..> AddFilterJob
DataSourceAddCalculatedColumnOperation ..> AddCalculatedColumnJob

interface DataSourceJob {

}

AddCalculatedColumnJob --> DataSourceJob
AddFilterJob --> DataSourceJob
CreateTransformationJob --> DataSourceJob
AddRowsTransformationJob --> DataSourceJob
AddColumnsTransformationJob --> DataSourceJob
@enduml