@startuml Job-Executor
skinparam DefaultTextAlignment center
title Job Executor

(*) --> "Traverse Jobs"
 
 if "status = READY" then
  --> [yes] skip
  --r-> "Traverse Jobs"
else
  --> [no] Check dependencies
  if "dependency status = Error" then
    --> [yes]Resolve current job as Error
    --> (*)
  else
    --> [no]execute job based on job type
    --> (*)
  endif
endif

@enduml