@startuml job-executor
skinparam DefaultTextAlignment center
title convert transformation to job queue

(*) --> [transformations]initialize job queue
    --> [for each transformation]"check transformation type"

if "type = create" then 
 --> [yes] add CreateTransformationJob to job queue
 --> convert operations to jobs\nthen add to job queue
else
    --> [no] convert it's dependency to jobs first\nthen add to job queue
    --> add add_rows or add_columns job to job queue\nsourceDependency = -dependency.length - 1
    --> convert operations to jobs\nthen add to job queue
    --> (*)
@enduml