@startuml transformation-canvas

left to right direction

interface TransformationResult {

}

class DataSourceCreateTransformation {

}

interface MatchedColumn {

}

enum DataSourceJoinMode {

}

class TransformationCanvasContext {
    -visible: boolean
    -currentStep: number
    -addType: 'ADD_ROWS' | 'ADD_COLUMNS'
    -source: Load<TransformationResult> | null
    -target: DataSourceCreateTransformation | null
    -matchedColumns: MatchedColumn[]
    -appliedTransformationId: string
    -joinMode: DataSourceJoinMode
    -allowPrevious: boolean

    +onAddRowsOrColumns(source: Load<TransformationResult>, addType, appliedTransformationId: string)
    +onUpdateAddRowsOrColumnSetting(source: Load<TransformationResult>, target: DataSourceCreateTransformation, addType, matchedColumns, appliedTransformationId, joinMode)
    +onImportData(t: DataSourceCreateTransformation)
    +hide()
    +next()
    +previous()
}

TransformationResult ..l-> TransformationCanvasContext::onAddRowsOrColumns
TransformationResult ..l-> TransformationCanvasContext::onUpdateAddRowsOrColumnSetting
DataSourceCreateTransformation ..u-> TransformationCanvasContext::onUpdateAddRowsOrColumnSetting
MatchedColumn ..u-> TransformationCanvasContext::onUpdateAddRowsOrColumnSetting
DataSourceJoinMode ..u-> TransformationCanvasContext::onUpdateAddRowsOrColumnSetting
DataSourceCreateTransformation ..> TransformationCanvasContext::onImportData

@enduml