@startuml transformation-config
left to right direction

interface DataSourceTransformation {

}
interface DataSourceOperation {

}

interface AddRowsOrColumnsSetting {

}

interface DataSourceOperationSetting {

}

interface TransformationResult {

}

class TransformationConfig {
    -transformations: DataSourceTransformation[]
    -selectedTransformationId: string
    -selectedOperationId: string

    +findPreviousTransformaion(id: string | DataSourceTransformation)
    +findPreviousOperation(operationId: string)
    +selectedResult()
    +selectedTransformation()
    +selectedOperation()
    +selectTransformation(id: string)
    +selectOperation(operationId: string)
    +updateAddRowsOrColumnTransformationSetting(id: string, setting: AddRowsOrColumnsSetting, result: Load<TransformationResult>
    +updateOperationSetting(operationId: string, setting: DataSourceOperationSetting)
    +addAddRowsOrColumnsTransformation(transformation: DataSourceTransformation, after: string)
    +addOperation(operation: DataSourceOperation, id: string, after: string = '')
    +removeTransformation(id: string)
    +removeOperation(operationId: string)
}
DataSourceTransformation ..-> TransformationConfig::transformations
TransformationResult ..-> TransformationConfig::updateAddRowsOrColumnTransformationSetting
DataSourceOperationSetting ..-> TransformationConfig::updateOperationSetting
AddRowsOrColumnsSetting ..-> TransformationConfig::updateAddRowsOrColumnTransformationSetting
DataSourceOperation ..-> TransformationConfig::addOperation

@enduml